### ISSUE TITLE
Tracking issue: refactor cluster mode

### ISSUE THREAD

**Issue by ZuLiangWang** [CeresDB/ceresmeta#145]
**Description**
The cluster mode of CeresDB has many defects at present, and we need a better distributed solution. We also need to refactor the current code to make the cluster mode of CeresDB more robust.

**Proposal**
- [ ] Support shard to transfer leader based on distributed lock using `etcd`. The modifications to the CeresDB section are in this pull request. https://github.com/CeresDB/ceresdb/pull/706
- [ ] Refactor scheduler module,  based on the new interaction model, use scheduler to manage the creation of procedures.
- [ ] Refactor procedure manager, support executing procedures in shard-level serial manner. (Need to support scenarios where one procedure is associated with multiple shards.) 
- [ ] Refactor all types of procedures to remove internal modifications to shard metadata and instead update them through heartbeat.

**Additional context**
